server:
  port: 8084

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: final_catalogs
      port: 27017 #puerto privado contenedor Docker, no el publico
      host: mongodb

queue:
  serie:
    name: Serie
  movie:
    name: Movie

resilience4j:
  circuitbreaker:
    instances:
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
      series: 
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        
  retry:
    instances:
      movies:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError
      series:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError

#Habilitamos el endpoint de actuator
management:
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Catalog Service created for exam
    version: 1.0.0
